### ISSUE TITLE
Extract the type of debate per speech

### ISSUE THREAD

**Issue by MansMeg** [welfare-state-analytics/riksdagen-corpus#15] opened 2021-01-22 08:02 UTC
In my analysis of the Swedish parliament, I used the different type of debates (party leader debates, interpolation debates, general debates). This is meta-data we most likely would like to have for all data. I know this is available back to 1994 at least in the digital corpus.

**Comment by ninpnin** [comment] 2021-11-03 10:27
Seems to be a duplicate of #37

**Closed by ninpnin** 2021-11-03 10:27 UTC
