### ISSUE TITLE
Corpus content linking to wrong page

### ISSUE THREAD

**Issue by rbbby** [welfare-state-analytics/riksdagen-corpus#124] opened 2022-02-15 10:07 UTC
When searching for more party mappings "(o)" I found that the contents in the corpus refer to the page linked below. When examining the page however it can be seen that the actual contents come from the next page. Not sure of the extent and implications of this problem.

https://betalab.kb.se/prot-198586--146/prot_198586__146-052.jp2/_view

**Comment by rbbby** [comment] 2022-02-15 10:11
Happens here as well:
https://betalab.kb.se/prot-197778--106/prot_197778__106-093.jp2/_view

**Comment by BobBorges** [comment] 2023-09-22 14:28
Duplicate of #298

**Closed as completed by BobBorges** 2023-09-22 14:28 UTC
