### ISSUE TITLE
Full unit testing of all XML-files agains schema

### ISSUE THREAD

**Issue by MansMeg** [welfare-state-analytics/riksdagen-corpus#399] opened 2023-10-25 08:08 UTC
Currently, we only test a small number of XML-files in the unit test to test XML files against the schema.

We should test all XML-documents at least when merging into main/master
Then we can either check all XML in dev or just the XML that has been changed compared to main. Probably check all is feasible if we run these tests in a separate instance on Action.

**Comment by BobBorges** [comment] 2023-10-25 08:17
Closing as duplicate of #395

**Closed as completed by BobBorges** 2023-10-25 08:17 UTC

**Comment by MansMeg** [comment] 2023-10-25 08:25
Great! Sorry for the duplicate!
