### ISSUE TITLE
Run a final sampling run on the quality of introductions

### ISSUE THREAD

**Issue by MansMeg** [welfare-state-analytics/riksdagen-corpus#90] opened 2021-12-01 08:21 UTC

**Comment by ninpnin** [comment] 2021-12-15 12:57
Previously, we have had a page-based sampling algorithm for this. What should we do now, as we probably want to also sample protocols from 1990->, which are digital and don't have pages per se?

**Comment by MansMeg** [comment] 2021-12-15 13:41
Hm. Yes, a good point. There are pages also for the later protocols, but they are not included right now.

I would:
1. Setup a new issue that also the later data need to have protocol pages linked to the data.
2. Just go with the protocols that have the pages for  now but file this issue as a new issue for the later data that we can check later on. Ie put the later protocols in the backlogg.

**Comment by ninpnin** [comment] 2021-12-15 14:29
I'm not sure if that exists, the original data is written in a digital format...? Or is there a link that you've seen them in?

**Comment by MansMeg** [comment] 2021-12-15 14:56
https://data.riksdagen.se/fil/71D8B389-B048-4282-BD34-3386E30992DD

An example.

**Comment by MansMeg** [comment] 2021-12-15 14:59
https://data.riksdagen.se/fil/0E59830C-0268-4269-BFC3-4A500275C386

Another example.

**Comment by ninpnin** [comment] 2023-05-03 13:45
Duplicate of quality assessment.

**Closed as completed by ninpnin** 2023-05-03 13:45 UTC

**Comment by salgo60** [comment] 2023-05-03 14:13
OT Robin has created WD records with 3 [P953 formats](https://www.wikidata.org/wiki/Property:P953) in WD see [Q98737483#P953](https://www.wikidata.org/wiki/Q98737483?uselang=en#P953) --> the page number just make sense for the pdf format...

[<img width="999" alt="image" src="https://user-images.githubusercontent.com/14206509/235941244-a8a590b5-f3f5-48b2-89db-b3c71bc74354.png">](https://www.wikidata.org/wiki/Q98737483?uselang=en#P953)
